name: sminez.github.io
description: >
    Innes Anderson-Morrison: Father, husband, programmer, photographer, teacher, musician, fool.
about: >
    This is my little corner of the internet.

master_repo: false
url: "sminez.github.io"
markdown: kramdown
highlighter: rouge
plugins: ['jekyll-paginate', 'jekyll-gist']
paginate: 4
logo: assets/jumpy.png
disqus_shortname: "sminez-github-io"

owner:
  name: sminez.github.io
  avatar: ""
  email: "innesdmorrison@gmail.com"
  twitter: "InnesMorrison"
  github: "sminez"
