title = "sminez.github.io"
description = "Thoughts and ideas: some better than others"
base_url = "https://sminez.github.io"

compile_sass = true
build_search_index = true
taxonomies = [
    {name = "tags", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
smart_punctuation = false
render_emoji = true

[extra]
toc_at_n_headings = 8
